### PR TITLE
fix(library-build): package.json should be copied in cross-platform way

### PR DESCRIPTION
**Pull request by hakimio**
We should use cross-platform way to copy files when building the library using "copyfiles" utility.

### CODE REVIEW

**Comment by willsoto** [comment]
Is `cp` not available in WSL?

**Comment by hakimio** [comment]
Haven't checked WSL, but if you just run it on default Windows cmd, it will definitely fail. Do you think many people use WSL?

**Comment by willsoto** [comment]
I’d like to think so. Are you on Windows and not using WSL?

**Comment by hakimio** [comment]
Yes, windows and no, I am not using it.
I can manually copy the files myself but I don't think other people trying to build the lib by just running "yarn build" will know that they have to do that before.

**Comment by willsoto** [comment]
Ok, fair enough

**Pull request merged**
