### PR TITLE
Angular 7

### PR DESCRIPTION
**Pull request by hakimio**
Recreated your project using latest version of Angular cli. 
* Now you have two projects: the library (projects/ng-chartist-lib) and the demo app (projects/ng-chartist-demo).
* Unit tests still pass
* Tslint tests also succeed
* Demo still runs as expected
* Added a couple more package.json scripts ("pack" and "package")
* Tried to keep all the other scripts the same way as they were before
* Couldn't get doc generator to work with Node 10, but should still work with older versions

Let me know if the changes look ok to you.

### CODE REVIEW

**Comment by hakimio** [comment]
Cool. Just remember to build the library before building/running the demo app.

**Comment by hakimio** [comment]
It seems the issue with typedoc wasn't related to node version. Anyway, it's fixed now as well.

**Comment by hakimio** [comment]
Can you also fix Greenkeeper?

**Comment by willsoto** [comment]
@hakimio Thanks again. I'll take a look at greenkeeper. I'll try and cut a release as well

**Comment by hakimio** [comment]
@willsoto You might want to remove "yarn-error.log" from npm package.
Also, can you update the demo website?

**Comment by hakimio** [comment]
@willsoto since you removed the README file from "projects/ng-chartist" folder, ng-chartist page on npmjs.com says "Unable to find a readme for ng-chartist@3.0.3".

Also, in your place I would keep 2 separate package.json files, since now the package.json in the npm package contains lots of stuff which shouldn't be there.

**Comment by willsoto** [comment]
@hakimio Good catch on the README, I'll fix that right now. Regarding two separate package.json I am not a fan of that since it just complicates the release process slightly from my perspective. I've moved everything into `devDependencies` so it shouldn't affect consumers at all.

**Comment by hakimio** [comment]
@willsoto What do you think about using compodoc instead of typedoc for documentations? It has better structure, better styling and it's easier to configure it.

Do you mind if I update README formatting?
Why are all the methods public in the ChartistComponent class? Is that on purpose?
Should we make reference to chartist object an observable variable?
Any idea why greenkeeper doesn't work? Is it because of the old version of "greenkeeper-lockfile"?

**Comment by willsoto** [comment]
@hakimio 

> What do you think about using compodoc instead of typedoc for documentations?

I don't have a strong opinion either way I suppose, I'd be open to a PR

> Do you mind if I update README formatting?

Anything in particular about the formatting? Just want more of an idea of what you mean

> Why are all the methods public in the ChartistComponent class? Is that on purpose?

It was probably because I didn't know better when I wrote the library originally.

> Any idea why greenkeeper doesn't work? Is it because of the old version of "greenkeeper-lockfile"?

Could be. I'll take a look at that soon.

**Comment by hakimio** [comment]
Basically, I want to make "Installation" and "Usage" sections in the readme look like in "cebor/angular-highcharts" library.

**Comment by willsoto** [comment]
Ok. I like that.

**Pull request merged**
