### PR TITLE
Tooltip plugin usage example

### PR DESCRIPTION
**Pull request by hakimio**
Adds tooltip plugin usage example. Closes issue #286.

### CODE REVIEW

**Comment by hakimio** [comment]
@willsoto why do you have the same things duplicated in github CI and CD workflows. Shouldn't CI be only "continuous integration" (build and tests) and CD "continuous delivery" (deployment) only?

**Comment by hakimio** [comment]
@willsoto Any idea why every github workflow action is run 3 times?

**Comment by willsoto** [comment]
@hakimio I wish I knew. I removed the `on push` workflow and made the `on pull request` review linear.

**Comment by hakimio** [comment]
@willsoto should we also remove gitlab pipeline status badge and update "gh-pages"?

**Comment by willsoto** [comment]
Sounds good to me! 👍

**Pull request merged**
